### ISSUE TITLE
Backend verwendet konfigurierbaren DB-Service name

### ISSUE THREAD

**Issue by tjorbo** [Dataport/terminfinder-helmCharts#19]
# Story
Als Softwarebetreiber möchte ich, dass der Service-Name, bei dem das Backend eine PostgresDB erwartet, konfiguriert werden kann um einen externen DB Service anbinden zu können

# Technische Details

global values:
```
global:
  postgresql:
    service:
      name: "" # if not set, default: "{{ Release.Name }}-postgres"
      ports:
        postgresql: 5432 # Default port 5432
```

# Akzeptanzkriterien

- [x] Die möglichkeit zur Konfiguration ist (wieder) gegeben

**Comment by tjorbo** [comment]
global.postgresql.service.name cannot be set - postgresql.nameOverride or postgresql.fullnameOverride will change the service name.

- [x] move config from global to postgresql to improve visibility

**Comment by martinclaus** [comment]
Als Alternative, die keinen Breaking Change zur Folge hat, könnte man eine zusätzliche Sektion in der values.yaml für externe Datenbanken erstellen, welche eine höhere Präzedenz hat, als der Service des Postgres Charts. E.g.:
```yaml
# terminfinder-chart/charts/terminfinder-backend/values.yaml
externalDatabase:
  address: null
  port: null
```

```yaml
# terminfinder-chart/charts/terminfinder-backend/templates/deployment.yaml
{{- $svc := .Values.externalDatabase.address | default (.Values.postgresql.fullnameOverride | trunc 63 | trimSuffix "-") | default (printf "%s-postgresql" .Release.Name) }}
```
Und analog für den Port.
